variables:
  REGISTRY_URL: 301722810093.dkr.ecr.ap-southeast-1.amazonaws.com
  IMAGE_REPO_PATH: ecs/demo-spring-boot
  CONTEXT: $CI_PROJECT_DIR
  AWS_REGION: ap-southeast-1
  MDS_DEVSECOPS_CROSS_ACCOUNT_RUNNER_IAM_ROLE_ARN: arn:aws:iam::301722810093:role/devsecops-cross-account-runner-role
  DEVSECOPS_CROSS_ACCOUNT_RUNNER_IAM_ROLE_EXTERNAL_ID: DFCOLLAB2021

stages:
  # - build-java
  - get-aws-token
  - build-image

get-aws-token:
  stage: get-aws-token
  image: 207818544005.dkr.ecr.ap-southeast-1.amazonaws.com/mcc-devsecops/aws-cli
  script:
    - CREDENTIALS=`aws sts assume-role --role-arn $MDS_DEVSECOPS_CROSS_ACCOUNT_RUNNER_IAM_ROLE_ARN --role-session-name RoleSession --output=json --external-id $DEVSECOPS_CROSS_ACCOUNT_RUNNER_IAM_ROLE_EXTERNAL_ID`
    - export AWS_ACCESS_KEY_ID=`echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId'`
    - export AWS_SECRET_ACCESS_KEY=`echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey'`
    - export AWS_SESSION_TOKEN=`echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken'`
    - export AWS_EXPIRATION=`echo ${CREDENTIALS} | jq -r '.Credentials.Expiration'`
    - echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN AWS_EXPIRATION=$AWS_EXPIRATION" > credentials
  artifacts:
    paths:
      - credentials
    expire_in: 1 days
  tags:
    - non-prod

# build-java:
#   stage: build-java
#   image: 207818544005.dkr.ecr.ap-southeast-1.amazonaws.com/mcc-devsecops/maven-corretto-17
#   script:
#     - mvn clean package
#   artifacts:
#     paths:
#       - target/
#     expire_in: 1 days

build-image:
  stage: build-image
  dependencies:
    - get-aws-token
    # - build-java
  image: 207818544005.dkr.ecr.ap-southeast-1.amazonaws.com/mcc-devsecops/kaniko
  script:
    - $(cat credentials)
    - mkdir -p /kaniko/.docker
    - echo "{\"credHelpers\":{\"$REGISTRY_URL\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - echo $REGISTRY_URL/$IMAGE:$CI_COMMIT_SHORT_SHA
    - /kaniko/executor --context $CONTEXT --dockerfile $CI_PROJECT_DIR/dockerfile --destination $REGISTRY_URL/$IMAGE_REPO_PATH:$CI_COMMIT_SHORT_SHA