aws:
  accessKey: acessKey
  secretKey: secretKey
  serviceEndpoint: ${LOCALSTACK_URL:http://localhost:4566}
  region: ap-southeast-1
  s3:
    bucketName: mybucket
    fileName: test.txt
  secretsmanager:
    secretId: MyTestSecret
config: 
  environment: ${ENVIRONMENT:local}
spring:
  datasource:
    url: jdbc:sqlserver://mssql:1433;encrypt=true;trustServerCertificate=true;databaseName=dockerdb
    username: sa
    password: Secret1234
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
app:
  db:
    init:
      enabled: false
